### ISSUE TITLE
Could include a simple example ?

### ISSUE THREAD

**Issue by jschaufele** [shellscape/apollo-log#5]
Documentation Is:

- [ x] Missing
- [x ] Needed
- [x ] Confusing
- [ ] Not Sure?

### Please Explain in Detail...
I am trying to figure out how to use this - it looks promising - does it only display to the console or does it also create a log file ?

**Comment by shellscape** [comment]
https://github.com/shellscape/apollo-log#usage

And the README states in the first paragraph:

> The console/terminal result of which will resemble the image below:

So there's both a clear example for how to use it, and where the logging is sent to, within the README.

**Comment by jschaufele** [comment]
Look I am trying to use your product and am sure you put a lot of work into it, I just don't understand how to invoke the logging - if you don't want to be more helpful then fine -

**Comment by shellscape** [comment]
It looks like you might be new to Github and possibly development in general, and that's cool. But the way you responded is neither welcome nor appropriate.

NPM packages frequently require at least _some_ understanding of a related technology. In this case, a cursory understanding of Apollo Server is required, as this is a package for use with it. Start there, that's what documentation and blog posts are for. But don't expect package authors to spoon feed you instructions on how to use underlying tech.
