### ISSUE TITLE
Using as plugin instead of extension

### ISSUE THREAD

**Issue by christiansaiki** [shellscape/apollo-log#7]
Is anything else required to use it as plugin instead of extension?
Just wondering because I think that the extensions are now deprecated in apollo-server

**Comment by shellscape** [comment]
Can you find a link to some docs that say extensions are deprecated? I'd be happy to update this to a plugin. I'm pretty sure that plugins expect a different structure to the export.

**Comment by christiansaiki** [comment]
Sorry, it will be only deprecated in v3
https://github.com/apollographql/apollo-server/blob/main/CHANGELOG.md#v2140
Is just that it seems that they are using the nomenclature `plugins` moving forward https://github.com/apollographql/apollo-server/pull/3998/files

**Comment by vith** [comment]
This is being printed on startup now:

`[deprecated] A "ApolloLogExtension" was defined within the "extensions" configuration for Apollo Server.  The API on which this extension is built ("graphql-extensions") is being deprecated in the next major version of Apollo Server in favor of the new plugin API.  See https://go.apollo.dev/s/plugins for the documentation on how these plugins are to be defined and used.`

**Comment by shellscape** [comment]
I'm actually going to be giving this package a refactor this week, at which point the extension will be removed. Keep an eye out for a new major version.
